apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logreader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: logreader
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: logreader
subjects:
- kind: ServiceAccount
  name: logreader # Name is case sensitive
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: logreader
  apiGroup: rbac.authorization.k8s.io