stages:
  - build
  - deploy
variables:
  REGISTRY: ""
  REGISTRY_NAMESPACE: ""
  REGISTRY_USER: ""
  APP_NAME: ""
  BUILD_SCRIPT: ""
  DOCKERFILE_URL: ""
  DEPLOY_SCRIPT: ""
  NAMESPACE: ""
  ################ OPTIONAL ###############
  # MVN_SETTINGS: "http://url/of/custom/mvn/settings.xml"
  # IMAGE_CLEAN: "true"
  ################ SECRET VARIABLES ###############
  # KUBECONFIG_CONTENT
  # REGISTRY_PASSWD or (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION)
  
  
build:
  stage: build
  image: zgwldrc/maven-and-docker
  cache:
    paths:
      - ".m2/repository"
  variables:
    MAVEN_OPTS: "-Dmaven.test.skip=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  script:
    - curl -s -o- $BUILD_SCRIPT | bash

deploy:test:
  environment:
    name: test
  image: zgwldrc/kubectl:v1.11.7
  stage: deploy
  when: manual
  variables:
    NAMESPACE: xx      
  script: |
      curl -s -o- $DEPLOY_SCRIPT | sh
