stages:
  - build
  - deploy:test
  - deploy:prod
variables:
  REGISTRY: ""
  REGISTRY_NAMESPACE: ""
  REGISTRY_USER: "AWS"
  APP_NAME: ""
  DOCKERFILE_URL: "https://raw.githubusercontent.com/zgwldrc/bcc/master/java-gitlab-ci-components/jar-dockerfile/Dockerfile"
  BUILD_SCRIPT: "https://raw.githubusercontent.com/zgwldrc/bcc/master/java-gitlab-ci-components/single-mod-project/10-build.sh"
  DEPLOY_SCRIPT: "https://raw.githubusercontent.com/zgwldrc/bcc/master/java-gitlab-ci-components/single-mod-project/20-deploy.sh"
  ################ OPTIONAL ###############
  # MVN_SETTINGS: "http://url/of/custom/mvn/settings.xml"
  # IMAGE_CLEAN: "true"
  ################ SECRET VARIABLES ###############
  # KUBECONFIG_CONTENT
  # REGISTRY_PASSWD or (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION)
before_script:
- |
  echo ${BASH_VERSION}
  echo "CI_COMMIT_SHA: ${CI_COMMIT_SHA}"
  echo "CI_COMMIT_TAG: ${CI_COMMIT_TAG}"
  echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"  
  
build:
  stage: build
  image: zgwldrc/maven-and-docker
  cache:
    paths:
      - ".m2/repository"
  variables:
    MAVEN_OPTS: "-Dmaven.test.skip=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  script:
    - curl -s -o- $BUILD_SCRIPT | bash

deploy:test:
  stage: deploy:test
  when: manual
  environment:
    name: test
  image: zgwldrc/kubectl:v1.11.7
  variables:
    GIT_STRATEGY: none
    CONTEXT: xx
  script: |
      curl -s -o- $DEPLOY_SCRIPT | sh

deploy:prod:
  stage: deploy:prod
  when: manual
  environment:
    name: prod
  image: zgwldrc/kubectl:v1.11.7
  variables:
    GIT_STRATEGY: none
    CONTEXT: xx
  script: |
      curl -s -o- $DEPLOY_SCRIPT | sh
