stages:
  - build
  - deploy
variables:
  APP_NAME: ""
  REGISTRY: ""
  REGISTRY_NAMESPACE: ""
  REGISTRY_USER: "AWS"
  DOCKERFILE_URL: "https://raw.githubusercontent.com/zgwldrc/bcc/master/javascript-frontend-gitlab-ci-components/Dockerfile"
  BUILD_SCRIPT: "https://raw.githubusercontent.com/zgwldrc/bcc/master/javascript-frontend-gitlab-ci-components/10-build.sh"
  DEPLOY_SCRIPT: "https://raw.githubusercontent.com/zgwldrc/bcc/master/javascript-frontend-gitlab-ci-components/21-deploy.sh"
  ################ SECRET VARIABLES ###############
  # KUBECONFIG_CONTENT
  # REGISTRY_PASSWD or (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION)

build:
  stage: build
  only:
  - master
  image: zgwldrc/npm-and-docker:awscli
  cache:
    paths:
      - node_modules/
  script:
  - |
    curl -s $BUILD_SCRIPT |bash

deploy:
  environment:
    name: prod
  image: zgwldrc/kubectl:v1.11.7
  stage: deploy
  when: manual
  variables:
    CONTEXT: xx
  script: |
      curl -s -o- $DEPLOY_SCRIPT | sh

