stages:
  - build
  - deploy
variables:
  REGISTRY: ""
  REGISTRY_NAMESPACE: ""
  REGISTRY_USER: ""
  APP_INFOS_URL: ""
  DOCKERFILE_URL: ""
  BUILD_LIST: "release-all"
  BUILD_SCRIPT: ""
  DEPLOY_SCRIPT: ""
  NAMESPACE: ""
  ################ OPTIONAL ###############
  # MVN_SETTINGS: "http://url/of/custom/mvn/settings.xml"
  # IMAGE_CLEAN: "true"
  # BUILD_EXCLUDE_LIST: "app1,app2,app3"
  # DEPLOY_EXCLUDE_LIST: "app1,app2,app3"
  ################ SECRET VARIABLES ###############
  # KUBECONFIG_CONTENT
  # REGISTRY_PASSWD or (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION)

build:
  only:
  - trigger
  stage: build
  image: zgwldrc/maven-and-docker
  cache:
    paths:
      - ".m2/repository"
  artifacts:
    paths:
      - deploy_list
      - build_list
  variables:
    MAVEN_OPTS: "-Dmaven.test.skip=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  script:
    - curl -s -o- $BUILD_SCRIPT | bash

deploy:test:
    environment:
      name: test
    image: zgwldrc/kubectl:v1.11.7
    only: 
    - trigger
    stage: deploy
    when: manual
    variables:
      NAMESPACE: xx
    script: |
        curl -s -o- $DEPLOY_SCRIPT | sh
