stages:
  - build
  - flyway
  - deploy

variables:
  REGISTRY: ""
  REGISTRY_NAMESPACE: ""
  REGISTRY_USER: "AWS"
  APP_INFOS_URL: ""
  DOCKERFILE_URL: "https://raw.githubusercontent.com/zgwldrc/bcc/master/java-gitlab-ci-components/jar-dockerfile/Dockerfile"
  BUILD_LIST: "release-all"
  BUILD_SCRIPT: "https://raw.githubusercontent.com/zgwldrc/bcc/master/java-gitlab-ci-components/multi-mod-project/10-build.sh"
  DEPLOY_SCRIPT: "https://raw.githubusercontent.com/zgwldrc/bcc/master/java-gitlab-ci-components/multi-mod-project/21-deploy.sh"
  DO_JOB_SCRIPT: "https://raw.githubusercontent.com/zgwldrc/bcc/master/java-gitlab-ci-components/multi-mod-project/30-do-job.sh"
  BUILD_EXCLUDE_LIST: ""
  DEPLOY_EXCLUDE_LIST: ""
  IMAGE_CLEAN: "true"
  ################ OPTIONAL ###############
  # MVN_SETTINGS: "http://url/of/custom/mvn/settings.xml"
  # IMAGE_CLEAN: "true"
  # BUILD_EXCLUDE_LIST: "app1,app2,app3"
  # DEPLOY_EXCLUDE_LIST: "app1,app2,app3"
  ################ SECRET VARIABLES ###############
  # KUBECONFIG_CONTENT
  # REGISTRY_PASSWD or (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION)
before_script:
- |
  echo ${BASH_VERSION}
  echo "CI_COMMIT_SHA: ${CI_COMMIT_SHA}"
  echo "CI_COMMIT_TAG: ${CI_COMMIT_TAG}"
  echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"

build:
  only:
  - trigger
  stage: build
  image: zgwldrc/maven-and-docker
  cache:
    paths:
      - ".m2/ "
  artifacts:
    paths:
      - deploy_list
      - build_list
  variables:
    MAVEN_OPTS: "-Dmaven.test.skip=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  script:
    - curl -s -o- $BUILD_SCRIPT | bash

flyway:
  stage: flyway
  only:
  - trigger
  when: manual
  image: zgwldrc/kubectl:v1.11.7
  variables:
    CONTEXT: <context>
    GIT_STRATEGY: none
    APP_NAME: <job-name>
  script:
  - curl -s -o- $DO_JOB_SCRIPT | sh

deploy:
  stage: deploy
  only: 
  - trigger
  when: manual
  environment:
    name: <context>
  image: zgwldrc/kubectl:v1.11.7
  variables:
    GIT_STRATEGY: none
    CONTEXT: <context>
  script: |
      curl -s -o- $DEPLOY_SCRIPT | sh
