#!/bin/bash
PROXY_SETTING="-x 127.0.0.1:1087"
TOKEN=""
BRANCH=""

BUILD_LIST="release-all"
REGISTRY=""
REGISTRY_NAMESPACE=""
REGISTRY_USER="AWS"
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_DEFAULT_REGION=""
DOCKERFILE_URL=""
APP_INFOS_URL=""
BUILD_SCRIPT=""
DEPLOY_SCRIPT=""
BUILD_EXCLUDE_LIST=""
DEPLOY_EXCLUDE_LIST=""

TRIGGER_URL=""
PIPELINES_URL=""

id=`curl $PROXY_SETTING -s -X POST \
    -F token=$TOKEN \
    -F "ref=$BRANCH" \
    -F "variables[BUILD_LIST]=$BUILD_LIST" \
    -F "variables[REGISTRY]=$REGISTRY" \
    -F "variables[REGISTRY_NAMESPACE]=$REGISTRY_NAMESPACE" \
    -F "variables[REGISTRY_USER]=$REGISTRY_USER" \
    -F "variables[AWS_ACCESS_KEY_ID]=$AWS_ACCESS_KEY_ID" \
    -F "variables[AWS_SECRET_ACCESS_KEY]=$AWS_SECRET_ACCESS_KEY" \
    -F "variables[AWS_DEFAULT_REGION]=$AWS_DEFAULT_REGION" \
    -F "variables[APP_INFOS_URL]=$APP_INFOS_URL" \
    -F "variables[DOCKERFILE_URL]=$DOCKERFILE_URL" \
    -F "variables[BUILD_SCRIPT]=$BUILD_SCRIPT" \
    -F "variables[DEPLOY_SCRIPT]=$DEPLOY_SCRIPT" \
    -F "variables[BUILD_EXCLUDE_LIST]=$BUILD_EXCLUDE_LIST" \
    -F "variables[DEPLOY_EXCLUDE_LIST]=$DEPLOY_EXCLUDE_LIST" \
    $TRIGGER_URL | jq '.id'`

open $PIPELINES_URL/$id
